import { useRouter } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useI18n } from '../src/i18n';
import { scheduleDebugNotification } from '../src/services/reminders';
import { useTimer } from '../src/state/TimerContext';

function ReminderCard({ label, title, body, enabled, detail, onSend }: { label: string; title: string; body: string; enabled: boolean; detail: string; onSend: () => void }) {
  return <View style={styles.card}><View style={styles.head}><Text style={styles.cardTitle}>{label}</Text><Text style={enabled ? styles.on : styles.off}>{enabled ? '已开启' : '未开启'}</Text></View><Text style={styles.copyTitle}>{title}</Text><Text style={styles.copy}>{body}</Text><Text style={styles.detail}>{detail}</Text><Pressable style={styles.send} onPress={onSend}><Text style={styles.sendText}>立即模拟此提醒（2 秒后）</Text></Pressable></View>;
}

export default function ReminderDebug() {
  const router = useRouter(); const timer = useTimer(); const { t } = useI18n();
  if (!__DEV__) { router.back(); return null; }
  const running = timer.tasks.filter(task => task.status === 'running');
  const send = (title: string, body: string, kind: 'start' | 'long', hours?: 2 | 3) => scheduleDebugNotification(title, body, kind, hours).then(() => Alert.alert('已安排', '会使用实际业务文案，在约 2 秒后送达。')).catch(() => Alert.alert('无法安排', '请检查本机通知权限。'));
  const setActivity = (hours: 2 | 3) => { timer.setReminderDebugActivity(Date.now() - hours * 3600000); Alert.alert('已更新', `最后任务状态操作时间已回拨 ${hours} 小时。`); };
  const startDetail = `${timer.reminders.startFrequency === 'weekdays' ? '工作日（周一至周五）' : '每天'} · ${String(timer.reminders.startHour).padStart(2, '0')}:${String(timer.reminders.startMinute).padStart(2, '0')}`;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.title}>提醒业务调试</Text><Text style={styles.note}>仅开发环境可见。所有“立即模拟”均采用用户实际会收到的标题和正文。</Text><View style={styles.status}><Text style={styles.statusTitle}>当前业务状态</Text><Text style={styles.statusLine}>运行任务：{running.length}{running.length === 1 ? ` · ${running[0].title}` : ''}</Text><Text style={styles.statusLine}>最后任务操作：{timer.lastTaskActivityAt ? new Date(timer.lastTaskActivityAt).toLocaleString() : '无'}</Text><Text style={styles.statusLine}>Live Activity：{running.length ? '应正在显示' : '无运行任务，不显示'}</Text></View><Text style={styles.section}>页面提示</Text><View style={styles.card}><Text style={styles.cardTitle}>已关闭提示：{timer.dismissedHints.length} 个</Text><Text style={styles.copy}>恢复 Today、History、Stats 页面底部被关闭的提示。</Text><Pressable style={styles.send} onPress={() => { timer.restoreHints(); Alert.alert('已恢复', '返回三个主页面即可再次看到提示。'); }}><Text style={styles.sendText}>恢复全部页面提示</Text></Pressable></View><Text style={styles.section}>本地通知</Text><ReminderCard label="开始工作提醒" title={t('reminders.startTitle')} body={t('reminders.startBody')} enabled={timer.reminders.startEnabled} detail={startDetail} onSend={() => send(t('reminders.startTitle'), t('reminders.startBody'), 'start')} /><ReminderCard label="持续记录 2 小时" title={t('reminders.twoHourTitle')} body={t('reminders.twoHourBody')} enabled={timer.reminders.longEnabled && running.length > 0} detail={running.length ? '条件：有运行任务，且 2 小时没有任务状态操作。' : '正式触发前需要至少一个运行任务。'} onSend={() => send(t('reminders.twoHourTitle'), t('reminders.twoHourBody'), 'long', 2)} /><Pressable style={styles.secondary} onPress={() => setActivity(2)}><Text style={styles.secondaryText}>回拨最后操作时间到 2 小时前</Text></Pressable><ReminderCard label="持续记录 3 小时" title={t('reminders.threeHourTitle')} body={t('reminders.threeHourBody')} enabled={timer.reminders.longEnabled && running.length > 0} detail={running.length ? '条件：有运行任务，且 3 小时没有任务状态操作；本轮最后一次提醒。' : '正式触发前需要至少一个运行任务。'} onSend={() => send(t('reminders.threeHourTitle'), t('reminders.threeHourBody'), 'long', 3)} /><Pressable style={styles.secondary} onPress={() => setActivity(3)}><Text style={styles.secondaryText}>回拨最后操作时间到 3 小时前</Text></Pressable><Text style={styles.section}>灵动岛 / 锁屏 Live Activity</Text><View style={styles.card}><Text style={styles.cardTitle}>{running.length ? '正在运行' : '未运行'}</Text><Text style={styles.copyTitle}>{running.length === 1 ? running[0].title : `正在进行 ${running.length} 个任务`}</Text><Text style={styles.copy}>{running.length ? '应显示当前连续工作时间与“暂停全部”。' : '启动任何任务后，会在 iOS 真机 Development Build 显示。'}</Text></View><Pressable style={styles.back} onPress={() => router.back()}><Text style={styles.secondaryText}>{t('common.cancel')}</Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#F7FAF8' }, content: { padding: 22, paddingTop: 68, paddingBottom: 44 }, title: { fontSize: 27, fontWeight: '800', color: '#183B35' }, note: { marginTop: 8, color: '#718780', lineHeight: 20 }, status: { marginTop: 22, padding: 16, borderRadius: 18, backgroundColor: '#E5F3EF', gap: 6 }, statusTitle: { fontSize: 15, fontWeight: '800', color: '#27534A' }, statusLine: { color: '#47655E', fontSize: 13 }, section: { marginTop: 27, marginBottom: 10, fontSize: 17, fontWeight: '800', color: '#31564E' }, card: { padding: 16, borderRadius: 18, backgroundColor: '#FFF', marginBottom: 10 }, head: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }, cardTitle: { color: '#294842', fontSize: 15, fontWeight: '800' }, on: { backgroundColor: '#DDF1EB', color: '#277263', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, fontSize: 11, fontWeight: '800' }, off: { backgroundColor: '#F0F3F2', color: '#758A84', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, fontSize: 11, fontWeight: '800' }, copyTitle: { color: '#183B35', fontSize: 16, fontWeight: '700' }, copy: { color: '#526C65', marginTop: 4, lineHeight: 19 }, detail: { color: '#82958F', fontSize: 12, marginTop: 11, lineHeight: 17 }, send: { marginTop: 14, borderRadius: 11, paddingVertical: 11, alignItems: 'center', backgroundColor: '#1F7A70' }, sendText: { color: '#FFF', fontWeight: '800', fontSize: 13 }, secondary: { marginTop: -2, marginBottom: 12, borderRadius: 12, padding: 12, alignItems: 'center', backgroundColor: '#E5F3EF' }, secondaryText: { color: '#1F7A70', fontWeight: '800', fontSize: 13 }, back: { marginTop: 24, alignItems: 'center', padding: 12 } });
