import { Ionicons } from '@expo/vector-icons';
import * as ImageManipulator from 'expo-image-manipulator';
import * as ImagePicker from 'expo-image-picker';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Image, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { TaskTagIcon } from '../src/components/TaskTagIcon';
import { getSystemIconImage, getTaskTagLabel, systemIconChoices, TaskTag, uncategorizedTagId } from '../src/constants/taskTags';
import { languageModeLabel, languageSettingsCopy, LanguageMode, useI18n } from '../src/i18n';
import { useTimer } from '../src/state/TimerContext';

import { colors } from '../src/constants/colors';
export default function Settings() {
  const router = useRouter(); const timer = useTimer(); const { locale, languageMode, setLanguageMode, t } = useI18n(); const [editing, setEditing] = useState<TaskTag | null>(null); const [isAdding, setIsAdding] = useState(false); const [name, setName] = useState(''); const [iconUri, setIconUri] = useState<string | undefined>(); const [systemIconId, setSystemIconId] = useState<string | undefined>(); const [compressing, setCompressing] = useState(false); const [languageVisible, setLanguageVisible] = useState(false);
  const closeEditor = () => { setEditing(null); setIsAdding(false); setName(''); setIconUri(undefined); setSystemIconId(undefined); };
  const openEditor = (category: TaskTag) => { if (category.id === uncategorizedTagId) return; setEditing(category); setName(getTaskTagLabel(category, locale)); setIconUri(category.iconUri); setSystemIconId(category.systemIconId ?? (systemIconChoices.some(icon => icon.id === category.id) ? category.id : undefined)); };
  const pickIcon = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { Alert.alert(t('settings.photoPermissionTitle'), t('settings.photoPermissionText')); return; } const picked = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Images, allowsEditing: true, aspect: [1, 1], quality: 1 }); if (picked.canceled) return; setCompressing(true); try { const image = await ImageManipulator.manipulateAsync(picked.assets[0].uri, [{ resize: { width: 128 } }], { compress: 0.7, format: ImageManipulator.SaveFormat.JPEG, base64: true }); if (image.base64) setIconUri(`data:image/jpeg;base64,${image.base64}`); } catch { Alert.alert(t('settings.iconProcessFailedTitle'), t('settings.iconProcessFailedText')); } finally { setCompressing(false); } };
  const save = () => { if (!name.trim()) return; if (editing) timer.updateCategory(editing.id, name, iconUri, systemIconId); else timer.addCategory(name, iconUri, systemIconId); closeEditor(); };
  const confirmDelete = (category: TaskTag) => { const count = timer.tasks.filter(task => task.tagId === category.id).length; Alert.alert(t('settings.deleteTitle', { label: getTaskTagLabel(category, locale) }), count ? t('settings.deleteWithTasks', { count }) : t('settings.deleteWithoutTasks'), [{ text: t('common.cancel'), style: 'cancel' }, { text: t('common.delete'), style: 'destructive', onPress: () => { timer.deleteCategory(category.id); closeEditor(); } }]); };
  const visible = Boolean(editing || isAdding); const preview = iconUri ? { uri: iconUri } : getSystemIconImage(systemIconId); const languageCopy = languageSettingsCopy(locale); const chooseLanguage = (mode: LanguageMode) => { setLanguageMode(mode); setLanguageVisible(false); };
  return <><ScrollView style={styles.page} contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back} accessibilityLabel={t('common.cancel')}><Ionicons name="chevron-back" size={23} color="#31564E" /></Pressable><Text style={styles.title}>{t('common.settings')}</Text><View style={styles.back} /></View><Text style={styles.sectionTitle}>{languageCopy.title}</Text><View style={styles.list}><Pressable onPress={() => setLanguageVisible(true)} style={styles.row}><View style={styles.languageIcon}><Ionicons name="language-outline" size={21} color="#1F7A70" /></View><View style={styles.grow}><Text style={styles.name}>{languageCopy.title}</Text><Text style={styles.meta}>{languageModeLabel(languageMode, locale)}</Text></View><Ionicons name="chevron-forward" size={18} color="#8AA09A" /></Pressable></View><Text style={styles.sectionTitle}>{t('settings.categoryManagement')}</Text><Text style={styles.note}>{t('settings.categoryNote')}</Text><View style={styles.list}>{timer.categories.map(category => { const label = getTaskTagLabel(category, locale); return <Pressable key={category.id} onPress={() => openEditor(category)} disabled={category.id === uncategorizedTagId} style={styles.row}><TaskTagIcon tagId={category.id} size={36} /><View style={styles.grow}><Text style={styles.name}>{label}</Text><Text style={styles.meta}>{category.id === uncategorizedTagId ? t('settings.systemCategory') : t('settings.taskCount', { count: timer.tasks.filter(task => task.tagId === category.id).length, taskWord: timer.tasks.filter(task => task.tagId === category.id).length === 1 ? t('common.task') : t('common.tasks') })}</Text></View><Ionicons name={category.id === uncategorizedTagId ? 'lock-closed-outline' : 'chevron-forward'} size={18} color="#8AA09A" /></Pressable>; })}</View><Pressable onPress={() => { setIsAdding(true); setName(''); }} style={styles.add}><Ionicons name="add" size={20} color="#1F7A70" /><Text style={styles.addText}>{t('settings.addCategory')}</Text></Pressable></ScrollView>
    <Modal visible={visible} transparent animationType="slide" onRequestClose={closeEditor}><Pressable style={styles.backdrop} onPress={closeEditor}><Pressable style={styles.sheet} onPress={event => event.stopPropagation()}><Text style={styles.sheetTitle}>{editing ? t('settings.editCategory') : t('settings.addCategory')}</Text><Text style={styles.label}>{t('settings.categoryName')}</Text><TextInput value={name} onChangeText={value => setName(value.slice(0, 12))} placeholder={t('settings.categoryNamePlaceholder')} style={styles.input} /><Text style={styles.label}>{t('settings.categoryIcon')}</Text><View style={styles.iconLine}><View style={styles.largeIcon}>{preview ? <Image source={preview} style={styles.image} /> : null}</View><Pressable onPress={pickIcon} disabled={compressing} style={styles.photo}><Text style={styles.photoText}>{compressing ? t('settings.compressing') : t('settings.chooseFromPhotos')}</Text></Pressable></View><View style={styles.grid}>{systemIconChoices.map(icon => <Pressable key={icon.id} onPress={() => { setSystemIconId(icon.id); setIconUri(undefined); }} style={[styles.icon, systemIconId === icon.id && !iconUri && styles.selected]}><Image source={getSystemIconImage(icon.id)} style={styles.image} /></Pressable>)}</View><Text style={styles.help}>{t('settings.iconHelp')}</Text><View style={styles.actions}>{editing ? <Pressable onPress={() => confirmDelete(editing)} style={styles.delete}><Text style={styles.deleteText}>{t('common.delete')}</Text></Pressable> : null}<Pressable onPress={closeEditor} style={styles.cancel}><Text>{t('common.cancel')}</Text></Pressable><Pressable onPress={save} style={styles.save}><Text style={styles.saveText}>{t('common.save')}</Text></Pressable></View></Pressable></Pressable></Modal><Modal visible={languageVisible} transparent animationType="slide" onRequestClose={() => setLanguageVisible(false)}><Pressable style={styles.backdrop} onPress={() => setLanguageVisible(false)}><Pressable style={styles.languageSheet} onPress={event => event.stopPropagation()}><Text style={styles.sheetTitle}>{languageCopy.title}</Text><Text style={styles.sheetSubtitle}>{languageCopy.subtitle}</Text>{(['auto', 'zh-CN', 'en'] as LanguageMode[]).map(mode => <Pressable key={mode} onPress={() => chooseLanguage(mode)} style={styles.languageOption}><Text style={styles.name}>{mode === 'auto' ? languageCopy.automatic : mode === 'zh-CN' ? languageCopy.chinese : languageCopy.english}</Text><Ionicons name={languageMode === mode ? 'checkmark-circle' : 'ellipse-outline'} size={22} color={languageMode === mode ? '#1F7A70' : '#A4B5B0'} /></Pressable>)}</Pressable></Pressable></Modal></>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},content:{padding:22,paddingTop:59,paddingBottom:42},header:{height:42,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:39,height:39,borderRadius:20,backgroundColor:'#EEF5F2',alignItems:'center',justifyContent:'center'},title:{fontSize:19,fontWeight:'800',color:'#183B35'},sectionTitle:{fontSize:26,fontWeight:'800',color:'#183B35',marginTop:28},note:{fontSize:14,color:'#7C918B',marginTop:6,marginBottom:22},list:{backgroundColor:'#FFFFFF',borderRadius:20,overflow:'hidden'},row:{minHeight:70,paddingHorizontal:17,flexDirection:'row',alignItems:'center',gap:13,borderBottomWidth:1,borderColor:'#EEF3F1'},languageIcon:{width:36,height:36,borderRadius:18,backgroundColor:'#EEF8F5',alignItems:'center',justifyContent:'center'},grow:{flex:1},name:{fontSize:15,fontWeight:'700',color:'#294842'},meta:{fontSize:12,color:'#82958F',marginTop:4},add:{height:56,borderRadius:17,borderWidth:1,borderColor:'#BFDCD4',backgroundColor:'#EEF8F5',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,marginTop:14},addText:{fontSize:15,fontWeight:'800',color:'#1F7A70'},backdrop:{flex:1,backgroundColor:'rgba(20,50,44,.3)',justifyContent:'flex-end'},sheet:{backgroundColor:'#FFFFFF',borderTopLeftRadius:28,borderTopRightRadius:28,padding:22,paddingBottom:38},languageSheet:{backgroundColor:'#FFFFFF',borderTopLeftRadius:28,borderTopRightRadius:28,padding:22,paddingBottom:38},sheetTitle:{fontSize:20,fontWeight:'800',color:'#183B35'},sheetSubtitle:{fontSize:13,color:'#80938E',marginTop:5,marginBottom:12},languageOption:{height:56,borderBottomWidth:1,borderBottomColor:'#EEF3F1',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},label:{fontSize:13,fontWeight:'700',color:'#526C65',marginTop:17,marginBottom:7},input:{height:48,borderRadius:13,borderWidth:1,borderColor:'#DDE9E5',paddingHorizontal:14,fontSize:16},iconLine:{flexDirection:'row',gap:14,alignItems:'center'},largeIcon:{width:66,height:66,borderRadius:18,backgroundColor:'#F4F8F6',overflow:'hidden'},image:{width:42,height:42,resizeMode:'contain'},photo:{padding:12,borderRadius:10,backgroundColor:'#EEF8F5'},photoText:{color:'#1F7A70',fontWeight:'700'},grid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:14},icon:{width:'18.3%',height:54,borderRadius:12,borderWidth:1,borderColor:'#E4ECE9',alignItems:'center',justifyContent:'center'},selected:{borderColor:'#1F7A70',backgroundColor:'#EAF6F2'},help:{fontSize:12,lineHeight:18,color:'#899B96',marginTop:10},actions:{flexDirection:'row',gap:9,marginTop:24},delete:{padding:14,borderRadius:13,backgroundColor:'#FFF0EF'},deleteText:{color:'#C85752',fontWeight:'800'},cancel:{flex:1,height:46,borderRadius:13,backgroundColor:'#EEF5F2',alignItems:'center',justifyContent:'center'},save:{flex:1,height:46,borderRadius:13,backgroundColor:'#1F7A70',alignItems:'center',justifyContent:'center'},saveText:{color:'#FFFFFF',fontWeight:'700'}});




