import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { TaskTagIcon } from '../../src/components/TaskTagIcon';
import { formatHistoryDay, formatShortTime, useI18n } from '../../src/i18n';
import { liveTask, Task, useTimer } from '../../src/state/TimerContext';
import { todayKey } from '../../src/utils/time';

const statusOrder: Record<Task['status'], number> = { running: 0, paused: 1, completed: 2, pending: 3 };

export default function History() {
  const timer = useTimer(); const { locale, t } = useI18n(); const [expandedDay, setExpandedDay] = useState<string | null>(null); const [editingTask, setEditingTask] = useState<Task | null>(null); const [allocatedMinutes, setAllocatedMinutes] = useState(''); const [timeError, setTimeError] = useState('');
  const groups = Object.entries(timer.tasks.reduce<Record<string, Task[]>>((all, task) => { (all[task.day] ??= []).push(task); return all; }, {})).map(([day, tasks]) => [day, [...tasks].sort((a, b) => statusOrder[a.status] - statusOrder[b.status])] as [string, Task[]]).sort(([a], [b]) => b.localeCompare(a));
  const openEditor = (task: Task) => { setEditingTask(task); setAllocatedMinutes(String(Math.round(task.allocatedDuration / 60000))); setTimeError(''); };
  const closeEditor = () => { setEditingTask(null); setTimeError(''); };
  const saveTimes = () => { const allocated = Number(allocatedMinutes); if (!editingTask || !Number.isInteger(allocated) || allocated < 0) { setTimeError(t('history.invalidMinutes')); return; } timer.updateAllocatedDuration(editingTask.id, allocated * 60000); closeEditor(); };
  const dayTitle = (day: string) => day === todayKey() ? t('stats.today') : formatHistoryDay(locale, day);
  return <><ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.title}>{t('history.title')}</Text><Text style={styles.subtitle}>{t('history.subtitle')}</Text>
    {groups.length ? groups.map(([day, tasks]) => { const expanded = day === expandedDay; const liveTasks = tasks.map(task => liveTask(task, timer, timer.now)); const work = liveTasks.reduce((sum, task) => sum + task.allocatedDuration, 0); const completed = tasks.filter(task => task.status === 'completed'); return <View key={day} style={styles.day}><Pressable accessibilityRole="button" accessibilityLabel={dayTitle(day)} accessibilityState={{ expanded }} onPress={() => setExpandedDay(current => current === day ? null : day)} style={styles.dayHeader}><View><Text style={styles.dayTitle}>{dayTitle(day)}</Text><Text style={styles.dayMeta}>{t('history.invested')} {formatShortTime(work, locale)} · {t('history.completed')} {completed.length}</Text></View><Ionicons name={expanded ? 'chevron-down' : 'chevron-forward'} size={18} color="#9DB0AA" /></Pressable>{expanded ? <View style={styles.rows}>{liveTasks.map(task => <View key={task.id} style={styles.row}><Pressable onLongPress={() => openEditor(task)} delayLongPress={450} style={styles.rowPress} accessibilityHint={t('history.editHint')}><View style={styles.rowHeading}><TaskTagIcon tagId={task.tagId} size={30} /><Text style={styles.rowTitle}>{task.title}</Text><Text style={styles.status}>{t(`history.statuses.${task.status}`)}</Text></View><Text style={styles.rowTime}>{t('history.invested')} {formatShortTime(task.allocatedDuration, locale)}</Text></Pressable><Pressable onPress={() => Alert.alert(t('task.delete'), task.title, [{ text: t('common.cancel'), style: 'cancel' }, { text: t('common.delete'), style: 'destructive', onPress: () => timer.remove(task.id) }])} style={styles.delete}><Ionicons name="trash-outline" size={17} color="#C85752" /></Pressable></View>)}</View> : null}</View>; }) : <View style={styles.empty}><Ionicons name="albums-outline" size={33} color="#A9C7C0" /><Text style={styles.emptyTitle}>{t('history.emptyTitle')}</Text><Text style={styles.emptyText}>{t('history.emptyText')}</Text></View>}</ScrollView>
    <Modal visible={editingTask !== null} transparent animationType="fade" onRequestClose={closeEditor}><View style={styles.modalBackdrop}><View style={styles.modalCard}><Text style={styles.modalTitle}>{t('history.editTime')}</Text><Text style={styles.modalTask} numberOfLines={1}>{editingTask?.title}</Text><Text style={styles.inputLabel}>{t('history.actualMinutes')}</Text><TextInput value={allocatedMinutes} onChangeText={setAllocatedMinutes} keyboardType="number-pad" selectTextOnFocus style={styles.timeInput} />{timeError ? <Text style={styles.error}>{timeError}</Text> : null}<View style={styles.modalActions}><Pressable onPress={closeEditor} style={styles.cancel}><Text style={styles.cancelText}>{t('common.cancel')}</Text></Pressable><Pressable onPress={saveTimes} style={styles.save}><Text style={styles.saveText}>{t('common.save')}</Text></Pressable></View></View></View></Modal></>;
}
const styles = StyleSheet.create({page:{flex:1,backgroundColor:'#F7FAF8'},content:{padding:22,paddingTop:65,paddingBottom:32},title:{fontSize:28,fontWeight:'800',color:'#183B35'},subtitle:{fontSize:14,color:'#7C918B',marginTop:6,marginBottom:26},day:{backgroundColor:'#FFF',borderRadius:20,marginBottom:13,borderWidth:1,borderColor:'#E8EFEC',overflow:'hidden'},dayHeader:{padding:17,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},dayTitle:{fontSize:16,fontWeight:'800',color:'#294842'},dayMeta:{fontSize:12,color:'#80938E',marginTop:5},rows:{borderTopWidth:1,borderTopColor:'#F0F4F2'},row:{minHeight:66,backgroundColor:'#FFF',flexDirection:'row',alignItems:'center'},rowPress:{flex:1,minHeight:66,paddingHorizontal:17,paddingVertical:8,justifyContent:'center'},rowHeading:{flexDirection:'row',alignItems:'center',gap:11},rowTitle:{flex:1,color:'#536C66',fontSize:14,fontWeight:'600'},status:{fontSize:11,color:'#849792'},rowTime:{fontSize:12,color:'#78908A',marginTop:4,marginLeft:41},delete:{padding:16},empty:{alignItems:'center',paddingTop:130},emptyTitle:{fontSize:16,fontWeight:'800',color:'#59736C',marginTop:14},emptyText:{fontSize:13,color:'#8A9E98',marginTop:7},modalBackdrop:{flex:1,backgroundColor:'rgba(20,50,44,.35)',justifyContent:'center',padding:24},modalCard:{backgroundColor:'#FFF',borderRadius:22,padding:22},modalTitle:{fontSize:19,fontWeight:'800',color:'#183B35'},modalTask:{color:'#718681',fontSize:14,marginTop:5,marginBottom:20},inputLabel:{color:'#526C65',fontSize:13,fontWeight:'700',marginBottom:7},timeInput:{height:46,borderWidth:1,borderColor:'#DDE9E5',borderRadius:12,paddingHorizontal:13,fontSize:16,color:'#183B35',marginBottom:15},error:{color:'#C85752',fontSize:12,marginTop:-4,marginBottom:10},modalActions:{flexDirection:'row',gap:10,marginTop:5},cancel:{flex:1,height:45,justifyContent:'center',alignItems:'center',backgroundColor:'#EEF5F2',borderRadius:12},cancelText:{color:'#527069',fontWeight:'700'},save:{flex:1,height:45,justifyContent:'center',alignItems:'center',backgroundColor:'#1F7A70',borderRadius:12},saveText:{color:'#FFF',fontWeight:'700'}});
