import { Ionicons } from '@expo/vector-icons';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Task, liveTask, useTimer } from '../state/TimerContext';
import { fullTime } from '../utils/time';
import { TaskTagIcon } from './TaskTagIcon';
import { formatShortTime, useI18n } from '../i18n';
import { SwipeDelete } from './SwipeDelete';

export function TaskCard({ task, onLongPress, onPress, isDragging = false }: { task: Task; onLongPress?: () => void; onPress?: () => void; isDragging?: boolean }) {
  const timer = useTimer(); const { locale, t } = useI18n(); const live = liveTask(task, timer, timer.now); const isRunning = task.status === 'running'; const breakLocked = Boolean(timer.breakState);
  let content: React.ReactNode;
  const editIcon = (size: number) => <Pressable onPress={onPress} onLongPress={onLongPress} delayLongPress={450} hitSlop={8} accessibilityRole="button" accessibilityLabel={t('task.edit', { title: task.title })}><TaskTagIcon tagId={task.tagId} size={size} /></Pressable>;
  const editTitle = (style: any, metaStyle?: any) => <Pressable onPress={onPress} onLongPress={onLongPress} delayLongPress={450} hitSlop={6} style={styles.titleButton} accessibilityRole="button" accessibilityLabel={t('task.edit', { title: task.title })}><Text numberOfLines={1} style={style}>{task.title}</Text>{metaStyle && live.allocatedDuration > 0 ? <Text numberOfLines={1} style={metaStyle}>{t('task.actualTime')} · {formatShortTime(live.allocatedDuration, locale)}</Text> : null}</Pressable>;
  if (task.status === 'completed') content = <Pressable onPress={onPress} onLongPress={onLongPress} delayLongPress={450} style={styles.completed}>{editIcon(27)}<Ionicons name="checkmark-circle" size={16} color="#86AAA0" />{editTitle(styles.completedTitle, styles.completedMeta)}<Pressable onPress={event => { event.stopPropagation(); timer.restart(task.id); }} hitSlop={8} style={styles.restart}><Ionicons name="refresh" size={15} color="#1F7A70" /><Text style={styles.restartText}>{t('task.restart')}</Text></Pressable></Pressable>;
  else if (!isRunning) { const action = task.status === 'paused' ? t('task.resume') : t('task.start'); content = <Pressable onPress={onPress} onLongPress={onLongPress} delayLongPress={450} style={styles.pending}>{editIcon(31)}{editTitle(styles.pendingTitle, styles.pendingMeta)}<Pressable onPress={event => { event.stopPropagation(); timer.start(task.id); }} hitSlop={8} style={styles.start} accessibilityLabel={`${action} ${task.title}`}><Ionicons name="play" size={12} color="#1F7A70" /><Text style={styles.startText}>{action}</Text></Pressable></Pressable>; }
  else content = <Pressable onPress={onPress} onLongPress={onLongPress} delayLongPress={450} style={styles.running}><View style={styles.heading}>{editIcon(32)}<View style={styles.pulse} />{editTitle(styles.runningTitle)}</View><View style={styles.times}><View><Text style={styles.caption}>{t('task.runningTime')}</Text><Text style={styles.elapsed}>{fullTime(live.elapsedDuration)}</Text></View><View style={styles.actual}><Text style={styles.caption}>{t('task.actualTime')}</Text><Text style={styles.allocated}>{fullTime(live.allocatedDuration)}</Text></View></View><View style={styles.actions}><Pressable onPress={event => { event.stopPropagation(); timer.pause(task.id); }} style={styles.secondary}><Ionicons name="pause" size={15} color="#43655F" /><Text style={styles.secondaryText}>{t('task.pause')}</Text></Pressable><Pressable onPress={event => { event.stopPropagation(); timer.complete(task.id); }} style={styles.complete}><Ionicons name="checkmark" size={16} color="#FFF" /><Text style={styles.completeText}>{t('task.complete')}</Text></Pressable></View></Pressable>;
  return <View style={[styles.cardShell, isDragging && styles.dragging, breakLocked && styles.locked]}><SwipeDelete enabled={!isDragging && !breakLocked} label={t('task.delete')} onDelete={() => timer.remove(task.id)}><View style={styles.card}>{content}</View></SwipeDelete></View>;
}

const styles = StyleSheet.create({
  cardShell:{marginBottom:9}, dragging:{opacity:.92}, locked:{opacity:.65}, card:{backgroundColor:'#FFF',borderRadius:22,overflow:'hidden'}, running:{borderRadius:22,padding:18,borderWidth:1,borderColor:'#D5E7E2',shadowColor:'#1E4A42',shadowOpacity:.06,shadowRadius:14,elevation:2}, heading:{flexDirection:'row',alignItems:'center',gap:10},pulse:{width:9,height:9,borderRadius:5,backgroundColor:'#38A890'},titleButton:{flex:1,minWidth:0,justifyContent:'center'},runningTitle:{fontSize:17,fontWeight:'700',color:'#183B35'},times:{flexDirection:'row',marginTop:18},actual:{marginLeft:48},caption:{fontSize:12,color:'#8A9C98',marginBottom:4},elapsed:{fontSize:25,fontWeight:'700',letterSpacing:.4,color:'#203E39'},allocated:{fontSize:25,fontWeight:'700',letterSpacing:.4,color:'#1F7A70'},actions:{flexDirection:'row',gap:10,marginTop:18},secondary:{flex:1,height:42,borderRadius:12,backgroundColor:'#F2F7F5',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:6},secondaryText:{fontSize:14,fontWeight:'700',color:'#43655F'},complete:{flex:1,height:42,borderRadius:12,backgroundColor:'#1F7A70',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:6},completeText:{fontSize:14,fontWeight:'700',color:'#FFF'},pending:{minHeight:70,borderRadius:17,paddingHorizontal:17,paddingVertical:8,alignItems:'center',flexDirection:'row',borderWidth:1,borderColor:'#EDF1EF',gap:14},pendingTitle:{fontSize:15,color:'#294842',fontWeight:'600'},pendingMeta:{fontSize:12,color:'#7C918B',marginTop:3},start:{minWidth:84,height:48,paddingHorizontal:13,borderRadius:12,backgroundColor:'#EEF8F5',justifyContent:'center',flexDirection:'row',gap:8,alignItems:'center'},startText:{color:'#1F7A70',fontSize:14,fontWeight:'700'},completed:{minHeight:70,flexDirection:'row',alignItems:'center',paddingHorizontal:12,paddingVertical:6,gap:9},completedTitle:{fontSize:14,color:'#81928D',textDecorationLine:'line-through'},completedMeta:{fontSize:12,color:'#81928D',marginTop:3},restart:{minWidth:88,height:48,paddingHorizontal:13,borderRadius:12,backgroundColor:'#EEF8F5',justifyContent:'center',flexDirection:'row',alignItems:'center',gap:8},restartText:{fontSize:13,fontWeight:'700',color:'#1F7A70'}
});
